"""
AI Release Notes Generator
Uses Claude API to auto-generate professional release notes from git commits.
Called automatically in CI/CD pipeline after every successful deployment.
"""

import subprocess
import json
import os
import datetime
import urllib.request
import urllib.error

# ─────────────────────────────────────────
#  Config
# ─────────────────────────────────────────
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
OUTPUT_FILE       = os.getenv("RELEASE_NOTES_FILE", "RELEASE_NOTES.md")
CLAUDE_MODEL      = "claude-sonnet-4-20250514"

# ─────────────────────────────────────────
#  Git helpers
# ─────────────────────────────────────────

def get_git_commits(since_tag: str = None, count: int = 20) -> list[dict]:
    """Get recent commits as structured data."""
    if since_tag:
        cmd = ["git", "log", f"{since_tag}..HEAD", "--pretty=format:%H|%s|%an|%ad", "--date=short"]
    else:
        cmd = ["git", "log", f"-{count}", "--pretty=format:%H|%s|%an|%ad", "--date=short"]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        commits = []
        for line in result.stdout.strip().split("\n"):
            if "|" in line:
                sha, subject, author, date = line.split("|", 3)
                commits.append({
                    "sha":     sha[:7],
                    "subject": subject,
                    "author":  author,
                    "date":    date
                })
        return commits
    except subprocess.CalledProcessError:
        return [{"sha": "unknown", "subject": "Initial release", "author": "dev", "date": str(datetime.date.today())}]


def get_latest_tag() -> str:
    """Get the most recent git tag."""
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return None


def get_current_version() -> str:
    """Generate semantic version from git tag or commit count."""
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--long"],
            capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        count = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            capture_output=True, text=True
        ).stdout.strip()
        return f"v1.0.{count or 0}"


# ─────────────────────────────────────────
#  Claude API call
# ─────────────────────────────────────────

def generate_release_notes_with_ai(commits: list[dict], version: str) -> str:
    """
    Call Claude API to generate professional release notes.
    Returns markdown-formatted release notes.
    """
    if not ANTHROPIC_API_KEY:
        print("⚠️  ANTHROPIC_API_KEY not set — using fallback generator")
        return generate_fallback_notes(commits, version)

    commit_lines = "\n".join(
        f"- [{c['sha']}] {c['subject']} ({c['author']}, {c['date']})"
        for c in commits
    )

    prompt = f"""You are a senior DevOps engineer writing professional release notes.

Given these git commits for version {version}:

{commit_lines}

Generate release notes in this EXACT markdown format:

## {version} — Release Notes
*Released: {datetime.date.today().strftime("%B %d, %Y")}*

### ✨ New Features
- (list features from feat: commits)

### 🐛 Bug Fixes
- (list fixes from fix: commits)

### ⚡ Performance
- (list from perf: commits)

### 🔒 Security
- (list from sec:/security: commits)

### 🏗️ Infrastructure
- (list from infra:/ci:/cd:/docker:/terraform: commits)

### 📦 Dependencies
- (list from deps: commits)

---
*Auto-generated by Claude AI · CI/CD Pipeline · Build #{os.getenv("BUILD_NUMBER", "local")}*

Rules:
- Be concise and professional
- Skip sections with no relevant commits
- Rewrite commit messages into user-friendly language
- Add brief impact notes where relevant (e.g., "improves response time by ~15%")
- Keep each bullet under 100 characters
"""

    payload = json.dumps({
        "model":      CLAUDE_MODEL,
        "max_tokens": 1000,
        "messages": [{"role": "user", "content": prompt}]
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data    = payload,
        headers = {
            "Content-Type":      "application/json",
            "x-api-key":         ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01"
        }
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
            return data["content"][0]["text"]
    except urllib.error.URLError as e:
        print(f"⚠️  Claude API error: {e} — using fallback")
        return generate_fallback_notes(commits, version)


# ─────────────────────────────────────────
#  Fallback (no API key)
# ─────────────────────────────────────────

def generate_fallback_notes(commits: list[dict], version: str) -> str:
    """Rule-based release notes if API key not available."""
    sections = {"feat": [], "fix": [], "perf": [], "sec": [], "infra": [], "other": []}

    for c in commits:
        subj = c["subject"]
        if subj.startswith("feat"):      sections["feat"].append(c)
        elif subj.startswith("fix"):     sections["fix"].append(c)
        elif subj.startswith("perf"):    sections["perf"].append(c)
        elif subj.startswith("sec"):     sections["sec"].append(c)
        elif any(subj.startswith(p) for p in ["infra", "ci", "cd", "docker", "terraform"]):
            sections["infra"].append(c)
        else:                            sections["other"].append(c)

    lines  = [f"## {version} — Release Notes"]
    lines += [f"*Released: {datetime.date.today().strftime('%B %d, %Y')}*\n"]

    labels = {
        "feat":  "✨ New Features",
        "fix":   "🐛 Bug Fixes",
        "perf":  "⚡ Performance",
        "sec":   "🔒 Security",
        "infra": "🏗️ Infrastructure",
        "other": "📦 Other Changes"
    }
    for key, header in labels.items():
        if sections[key]:
            lines.append(f"\n### {header}")
            for c in sections[key]:
                lines.append(f"- [{c['sha']}] {c['subject']}")

    lines.append(f"\n---")
    lines.append(f"*Build #{os.getenv('BUILD_NUMBER', 'local')} · Commit: {commits[0]['sha'] if commits else 'unknown'}*")
    return "\n".join(lines)


# ─────────────────────────────────────────
#  DORA Metrics tracker
# ─────────────────────────────────────────

def update_dora_metrics(version: str, success: bool, duration_s: int):
    """
    Append a deployment record to metrics.json.
    Dashboard reads this file to show DORA metrics.
    """
    metrics_file = "metrics.json"
    try:
        with open(metrics_file) as f:
            data = json.load(f)
    except FileNotFoundError:
        data = {"deployments": []}

    data["deployments"].append({
        "version":    version,
        "timestamp":  datetime.datetime.utcnow().isoformat() + "Z",
        "success":    success,
        "duration_s": duration_s,
        "build":      os.getenv("BUILD_NUMBER", "local"),
        "commit":     os.getenv("GIT_COMMIT", "unknown")[:7],
        "environment": os.getenv("ENVIRONMENT", "production")
    })

    with open(metrics_file, "w") as f:
        json.dump(data, f, indent=2)

    print(f"📊 DORA metrics updated: {metrics_file}")


# ─────────────────────────────────────────
#  Main
# ─────────────────────────────────────────

def main():
    print("🤖 AI Release Notes Generator — Starting")
    print("─" * 50)

    version  = get_current_version()
    last_tag = get_latest_tag()
    commits  = get_git_commits(since_tag=last_tag, count=20)

    print(f"📦 Version:  {version}")
    print(f"🏷️  Last tag: {last_tag or 'none'}")
    print(f"📝 Commits:  {len(commits)} found")

    notes = generate_release_notes_with_ai(commits, version)

    with open(OUTPUT_FILE, "w") as f:
        f.write(notes)

    print(f"✅ Release notes saved to: {OUTPUT_FILE}")
    print("─" * 50)
    print(notes[:300] + "...")

    # Update DORA metrics
    build_dur = int(os.getenv("BUILD_DURATION_SECONDS", "108"))
    update_dora_metrics(version=version, success=True, duration_s=build_dur)


if __name__ == "__main__":
    main()
